#!/usr/bin/env bash

set -e

snap start amazon-ssm-agent

apt-get update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io unzip

usermod -aG docker ubuntu

mkdir azure-devops-agent && cd azure-devops-agent
curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.154.1/vsts-agent-linux-x64-2.154.1.tar.gz;tar -zxvf vstsagent.tar.gz
./bin/installdependencies.sh
export AGENT_ALLOW_RUNASROOT=1
./config.sh --unattended --url https://dev.azure.com/MAT-OCS/ --auth pat --token ${azure_devops_agent_token} --projectname ${project_name} --runasservice --pool ${project_name}


chown ubuntu:ubuntu -R /azure-devops-agent

sudo ./svc.sh install
sudo ./svc.sh start
